[build-system]
requires = [
            "setuptools==80.10.1",
            "wheel",
            "Cython==3.2.4",
            "vswhere",
            "patch",
            "packaging",
            "setuptools-scm"
            ]

[tool.autopep8]
max_line_length = 120
ignore = [
         "E501",
         "W6"
         ]
in-place = true
recursive = true
aggressive = 3

[tool.pylint.'MESSAGES CONTROL']
disable = [
           "C0116", # Missing function or method docstring
           "C0114", # Missing module docstring
           "W1203", # Use lazy % formatting in logging functions (logging-fstring-interpolation)
           "R0913", # Too many arguments (x/y) (too-many-arguments),
           "C0103", # snake_case naming style
          ]

[tool.pylint.format]
max-line-length = 120

[tool.black]
line-length = 120
exclude = "tools/resources/*|src/submodules/*|env|venv|.eggs/*"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v --cov=src --cov-report=html"
testpaths = [
    "tests/unit",
]
pythonpath = [
    "src/ltrace",
    "src/modules",
    "src/submodules/porespy",
    "src/submodules/biaep",
    "src/submodules/py_pore_flow",
    "src/submodules/pyflowsolver"
]
env = [
    "QT_QPA_PLATFORM = offscreen"
]
filterwarnings = [
    "ignore:Type PySide2\\..* uses PyType_Spec with a metaclass that has custom tp_new:DeprecationWarning",
    "ignore:The hookimpl CovPlugin\\..* uses old-style configuration options:pytest.PytestDeprecationWarning",
]

[tool.pylic]
safe_licenses = [
    "3-Clause BSD License",
    "Apache 2.0",
    "Apache License 2.0",
    "Apache Software License",
    "Apache-2.0",
    "Apache-2.0 OR BSD-3-Clause",
    "BSD",
    "BSD License",
    "BSD-2-Clause",
    "BSD 2-clause",
    "BSD-3-Clause, Apache-2.0, dependency licenses",
    "BSD-3-clause",
    "FreeBSD",
    "GNU General Public License v2 (GPLv2)",
    "GNU General Public License v3 (GPLv3)",
    "GNU Lesser General Public License v2 (LGPLv2)",
    "GNU Lesser General Public License v2 or later (LGPLv2+)",
    "GNU Library or Lesser General Public License (LGPL)",
    "ISC License (ISCL)",
    "LGPL-2.1-only",
    "LGPL-2.1-or-later",
    "LGPL-3.0-only",
    "MIT",
    "MIT License",
    "MIT-CMU",
    "Mozilla Public License 2.0 (MPL 2.0)",
    "MPL-2.0 AND MIT",
    "Other/Proprietary License",
    "PSF-2.0",
    "Proprietary",
    "Public Domain",
    "Python Software Foundation License",
    "GNU Lesser General Public License v3 (LGPLv3)",
    "BSD 3-Clause",
    "LGPL",
    "LGPL-3.0",
    "CC-BY-4.0",
    "LicenseRef-NVIDIA-SOFTWARE-LICENSE",
]

unsafe_packages = [
    "edt",
    "google-crc32c",
    "matplotlib-inline",
    "namex",
    "pyflowsolver",
    "requests-unixsocket",
    "tools",
    "py_pore_flow",
    "ltrace",
    "modules",
    "mrml",
    "cuda-toolkit"
]
