; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "GeoSlicer_addon"
#define MyAppVersion "0.1"
#define MyAppPublisher "LTrace Technologies"
#define MyAppURL "https://www.ltrace.com.br/geoslicer/"
#define MyAppExeName "MyProg-x64.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{475EC5FF-55A0-49C6-850D-36E30C7687EB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=.
OutputBaseFilename=GeoSlicer_addon
SolidCompression=no
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "menu_ltrace.svg"; DestDir: {app}; Flags: dontcopy
Source: "plugin_to_geolog.py"; DestDir: {app}; Flags: dontcopy
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Code]
var
  PathsPage: TInputDirWizardPage;
  GeologPath: string;
  GeoSlicerPath: string;

function GetFirstMatchingDir(const BasePath, Pattern: string): string;
var
  FindRec: TFindRec;
begin
  Result := 'False'; // Default return value

  if FindFirst(ExpandConstant(BasePath + '\*'), FindRec) then
  begin
    repeat
      if ((FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0) and
         (FindRec.Name <> '.') and (FindRec.Name <> '..') then
      begin
        if Pos(Pattern, FindRec.Name) > 0 then
        begin
          Result := BasePath + '\' + FindRec.Name;
          FindClose(FindRec);
          Exit;
        end;
      end;
    until not FindNext(FindRec);
    FindClose(FindRec);
  end;
end;

procedure InitializeWizard();
var
  match: string;
begin
  PathsPage := CreateInputDirPage(
    wpSelectDir, // Show after the default directory selection
    'This will install a Ltrace (Geoslicer) item to the menu Processing of the Geolog apllication.',
    '',
    'Please browse and select the folders containing, respectively, GeoSlicer.exe and the Geolog installation',
    False,
    ''
  );
  PathsPage.Add('Select the path where GeoSlicer.exe is located');
  
  PathsPage.Add('Select the path where Geolog is installed');

  match := GetFirstMatchingDir(ExpandConstant('{commonpf64}\Paradigm'), 'Geolog')
  if match <> 'False' then
    PathsPage.Values[1] := match
  else
    begin
      match := GetFirstMatchingDir(ExpandConstant('{commonpf32}\Paradigm'), 'Geolog');
      if match <> 'False' then
        PathsPage.Values[1] := match;
    end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  // Save the user input when they proceed
  if CurPageID = PathsPage.ID then
    GeoSlicerPath := PathsPage.Values[0];
    GeologPath := PathsPage.Values[1];
  Result := True;
end;
  
function GetGeologPath(Param: string): String;
begin
  Result := GeologPath;
end;

function GetScriptParameters(Param: string): string;
begin
  ExtractTemporaryFile('plugin_to_geolog.py');
  ExtractTemporaryFile('menu_ltrace.svg');
  Result := Format('"%s\plugin_to_geolog.py" --geolog-path "%s" --geoslicer-path "%s"', [ExpandConstant('{tmp}'), GeologPath, GeoSlicerPath]);
end;
  
function GetGeoSlicerPythonExePath(Param: string): string;
begin
  Result := ExpandConstant(GeoSlicerPath + '\bin\python-real.exe');
end;

[Run]
Filename: "{code:GetGeoSlicerPythonExePath}"; \
Parameters: "{code:GetScriptParameters}"; \
WorkingDir: "{app}"
//Flags: runhidden